frecon: Move get_monotonic_time_ms to util.c
get_monotonic_time_ms is declared as inline and therefore
is not included in any object files.
This breaks linking in coverage builds.

Therefore move it to util.c instead of util.h so that object files
have an copy of the function get_monotonic_time_ms.

Fixes following linker error with USE=coverage.
dbus.pie.o:dbus.c:__profd_get_monotonic_time_ms:
 error: undefined reference to 'get_monotonic_time_ms'

BUG=chromium:961510
TEST=USE=coverage emerge-amd64-generic frecon works.

Change-Id: Ib2c5d223d448d39f5a86f29862221e86056bf38b