fix implicit decl errors
Some files use funcs but don't include the headers they need.
This works because some libpng headers include them implicitly,
but with newer libpng versions, that's no longer the case.

.../frecon/dbus.c:199:3: error: implicit declaration
      of function 'usleep' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                usleep(DBUS_WAIT_DELAY_US);

.../frecon/dev.c:97:9: error: implicitly declaring
      library function 'strcmp' with type 'int (const char *, const char *)'
      [-Werror,-Wimplicit-function-declaration]
                        if (!strcmp("input", udev_device_get_subsystem(dev))) {

BUG=chromium:599917
TEST=build works again

Change-Id: I3e74b6ccb6b9c6d22e7b0a7b1778576237412f85