Update patch set 1
Patch Set 1:

NOTE: The Commit Queue will retry your change automatically.

The following build(s) failed:

panther_embedded-minimal-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in http://build.chromium.org/p/chromiumos/builders/panther_embedded-minimal%20paladin/builds/2816

x86-mario-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/x86-mario%20paladin/builds/7887

beaglebone-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/beaglebone%20paladin/builds/7704

wolf-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/wolf%20paladin/builds/8683

leon-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/leon%20paladin/builds/8118

whirlwind-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/whirlwind%20paladin/builds/3146

smaug-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/smaug%20paladin/builds/1512

lumpy-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/lumpy%20paladin/builds/22638

x86-zgb-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/x86-zgb%20paladin/builds/4240

falco-full-compile-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/falco-full-compile%20paladin/builds/3475

storm-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/storm%20paladin/builds/5389

nyan-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/nyan%20paladin/builds/7125

stumpy-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/stumpy%20paladin/builds/22676

x86-generic-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in http://build.chromium.org/p/chromiumos/builders/x86-generic%20paladin/builds/23944

x86-alex-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/x86-alex%20paladin/builds/22117

amd64-generic-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in http://build.chromium.org/p/chromiumos/builders/amd64-generic%20paladin/builds/23741

rush_ryu-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/rush_ryu%20paladin/builds/4511

oak-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/oak%20paladin/builds/1648

veyron_pinky-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/veyron_pinky%20paladin/builds/4831

auron-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/auron%20paladin/builds/4804

daisy_spring-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/daisy_spring%20paladin/builds/9624

stout-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/stout%20paladin/builds/16701

parrot-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/parrot%20paladin/builds/17351

nyan-full-compile-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/nyan-full-compile%20paladin/builds/3475

daisy_skate-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/daisy_skate%20paladin/builds/4244

daisy-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/daisy%20paladin/builds/20367

lakitu_mobbuild-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/lakitu_mobbuild%20paladin/builds/494

samus-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/samus%20paladin/builds/8119

panther-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/panther%20paladin/builds/7562

peppy-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/peppy%20paladin/builds/9512

peach_pit-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/peach_pit%20paladin/builds/10083

strago-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/strago%20paladin/builds/1509

lakitu-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/lakitu%20paladin/builds/812

tricky-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/tricky%20paladin/builds/2595

link-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/link%20paladin/builds/22678

kayle-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/kayle%20paladin/builds/4480

guado_moblab-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/guado_moblab%20paladin/builds/274

x86-mario-nowithdebug-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/x86-mario-nowithdebug%20paladin/builds/7386

falco-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/falco%20paladin/builds/9529

rambi-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/rambi%20paladin/builds/7567

nyan_freon-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/nyan_freon%20paladin/builds/5079

butterfly-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/butterfly%20paladin/builds/16694

monroe-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in https://uberchromegw.corp.google.com/i/chromeos/builders/monroe%20paladin/builds/7567

gizmo-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in http://build.chromium.org/p/chromiumos/builders/gizmo%20paladin/builds/5080

arm-generic-paladin: The DetectIrrelevantChanges stage failed: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'splitlines' in http://build.chromium.org/p/chromiumos/builders/arm-generic%20paladin/builds/4017

The build failure may have been caused by infrastructure issues and/or bad chromiumos/chromite changes.

One of the following changes is probably at fault: CL:294553 CL:296051 CL:300253

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1